/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define RCC_BASE_ADDR 0x40023800UL
#define RCC_CFGR_REG_OFFSET  0x08UL

#define RCC_CFGR_REG_ADDR (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)
#define GPIO_BASE_ADDR 0x40020000UL



int main(void)
{
	uint32_t *pRccCfgrReg = (uint32_t *) RCC_CFGR_REG_ADDR;

	// configure rcc mco1 bitfield to select hsi clock source
	*pRccCfgrReg &= (0x3 <<21);

	// cofigure pA8 to be MCO signal
	uin32_t *pRCCAhb1Enr = (uint32_t *)(RCC_BASE_ADDR + 0x30);

	//enable gpioA
	*pRCCAhb1Enr |= (1 << 0);
	//set pa8 as alternate mode
	uint32_t *pGPIOAModeReg = (uint32_t *)(GPIO_BASE_ADDR + 00);

	*pGPIOAModeReg &= ~(0x03 << 16); // clear
	*pGPIOAModeReg |=(0x2 << 16); // set


	//configure alternate function register to set mode 0 for PA8
	uint32_t *pGPIOAAltFunHighReg = (uint32_t *)(GPIO_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= ~(0xf << 0 );



    /* Loop forever */
	for(;;);
}
